import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "../blocks/header/Header";
import Banner from "../blocks/banner/Banner";
import AboutThis from "../blocks/aboutThis/AboutThis";
import Process from "../blocks/process/Process";
import Footer from "../blocks/footer/Footer";

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Bubble Cards</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />
        <Banner />
        <AboutThis />
        <Process />
        <Footer />
      </main>
    </>
  );
}
